language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.7 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.1
        - python -m pip install --upgrade pip
        - pip3 install pipenv
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: "Python 3.7 on Linux"         
      python: 3.7     
      before_install:
        - sudo apt install libsdl2-dev libfreetype6-dev libsdl2-mixer-dev libsdl2-image-dev libsdl2-ttf-dev libjpeg-dev libpng-dev libportmidi-dev
        - python -m pip install --upgrade pip
        - pip3 install pipenv
install: python3 -m pipenv install || python -m pipenv install
script: python3 -m pipenv run python -m unittest unittests || python -m pipenv run python -m unittest unittests
